Blog/urls.py
from django.conf.urls import url, include
from .views import BlogView, BlogList, BlogDetail

app_name = 'Blog'
urlpatterns = [
    url(r'^test/$', BlogView.as_view(), name='blog-view'),
    url(r'^$', BlogList.as_view(), name = 'blog-list'),
    url(r'^detail/(?P<pk>\d+)/$', BlogDetail.as_view(), name = 'blog-detail')

]

Demos/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('apps.urls')),
    url(r'^zakupki/', include('Zakupki.urls'), name = 'zakupki'),
    url(r'^dostavka/', include('Dostavka.urls'), name = 'dostavka'),
    url(r'^blog/', include('Blog.urls'), name='blog'),
]

Dostavka/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *

app_name = 'dostavka'

urlpatterns = [
    #url(r'^$', views.index ),
    url(r'^$', DostavkaList.as_view(), name = 'list'),
    url(r'^today/$', Dostavka_today, name = 'today'),
    url(r'^add/$', Dostavka_add, name = 'add'),
    #url(r'^detail/(?P<pk>\d+)/$', DostavkaDetail.as_view(), name='detail'),
    url(r'^detail/(?P<id>\d+)/$', DostavkaDetail, name='detail'),

]

Dostavka/models.py
from django.db import models

# Create your models here.
class Dostavka(models.Model):
	create_at = models.DateField(auto_now=True)
	data_dostavki = models.DateField(auto_now=False, verbose_name='Дата доставки')
	company =models.CharField(max_length=50, verbose_name='Компания')
	adress = models.TextField(verbose_name='Адрес')
	score = models.CharField(max_length=20, verbose_name='Счет')
	note = models.TextField(verbose_name='Примечание')
	manager = models.CharField(max_length=30, verbose_name='Менеджер')
	is_active = models.BooleanField(default=False)

	class Meta:
		verbose_name = 'Доставка'
		verbose_name_plural = 'Доставки'

	def __str__(self):
		return self.company

Dostavka/forms.py
from django import forms
from django.forms import widgets
from .models import Dostavka


class DostavkaForm(forms.ModelForm):
    class Meta:
        model = Dostavka
        fields = '__all__'
        exclude = ['is_active']

        widgets = {
            'data_dostavki': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'дд.мм.гггг'}),
            'company': widgets.TextInput(attrs={'class': 'form-control'}),
            'adress': widgets.Textarea(attrs={'cols': 45, 'rows': 2, 'class': 'form-control'}),
            'score': widgets.TextInput(attrs={'class': 'form-control'}),
            'note': widgets.Textarea(attrs={'cols': 45, 'rows': 2, 'class': 'form-control'}),
            'manager': widgets.TextInput(attrs={'class': 'form-control'}),

        }

Dostavka/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Dostavka
from .forms import DostavkaForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import date

#def test_list(request):
#	for_list = Dostavka.objects.all()
#	return render(request, 'dostavka.html', locals())
# Create your views here.

class DostavkaList(ListView):
	template_name = 'dostavka_new.html'
	context_object_name = 'dostavka'
	model = Dostavka

	def dispatch(self, request, *args, **kwargs):
#		#self.form = ZakupkiNewForm(request.GET)
#		#self.form.is_valid()
		self.test_field = request.GET.get('test_field')
		self.search = request.GET.get('search')
		return super(DostavkaList, self).dispatch(request, *args, **kwargs)

	def get_queryset(self):
		dostavka = Dostavka.objects.all()
		if self.search:
			dostavka = dostavka.filter(score=self.search)
		if self.test_field:
			dostavka = dostavka.order_by(self.test_field)
		return dostavka

#	def get_queryset(self):
#		dostavka = Dostavka.objects.all()
#		paginator = Paginator(dostavka, 20)
#		page = self.request.GET.get('page')
#		try:
#			if self.search:
#				dostavka = dostavka.filter(score=self.search)
#			if self.test_field:
#				dos = dostavka.order_by(self.test_field)
#			dostavka = paginator.page(page)
#			# If page is not an integer, deliver first page.
#			if self.search:
#				dostavka = dostavka.filter(score=self.search)
#			if self.test_field:
#				dostavka = dostavka.order_by(self.test_field)
#			dostavka = paginator.page(1)
#		except EmptyPage:
#			# If page is out of range (e.g. 9999), deliver last page of results.
#			if self.search:
#				dostavka = dostavka.filter(score=self.search)
#			if self.test_field:
#				dostavka = dostavka.order_by(self.test_field)
#			dostavka = paginator.page(paginator.num_pages)
#		return dostavka

def Dostavka_today(request):
	now = date.today()
	now = now.strftime('%Y-%m-%d')
	dostavka = Dostavka.objects.filter(data_dostavki = now)
	return render(request, 'dostavka_today.html', locals())

def Dostavka_add(request):
	if request.method == 'POST':
		form = DostavkaForm(request.POST or None)
		if form.is_valid():
			new_form = form.save()
			return redirect('../')
	else:
		form = DostavkaForm()
	return render(request, 'dostavka_add.html', locals())

#class DostavkaDetail(DetailView):
#	template_name = 'dostavka_detail.html'
#	model = Dostavka

def DostavkaDetail(request, id):
	info = Dostavka.objects.get(id = id)
	form = DostavkaForm(request.POST or None, instance=info)
	if form.is_valid():
		form.save()
		return redirect("/dostavka")
	return render(request, 'dostavka_detail.html', locals())

#	def dispatch(self, request, *args, **kwargs):
#		dostavka = Dostavka.objects.get(id=id)
#		form = DostavkaForm(request.POST or None, instance=dostavka)
#		if form.is_valid():
#			form.save()
#			return redirect('/')
#		else:
#			form = DostavkaForm()
#		return (form)

templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">
    <title>B2b system for Demosgroup</title>
    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/style.css">
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">B2b system</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Главная</a></li>
            <li><a href="/zakupki/">Закупки</a></li>
            <li><a href="/dostavka/">Доставка</a></li>
            <li><a href="/blog/">Блог</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container-fluid">
        {% block blog %}{% endblock %}
        {% block contaner %}{% endblock %}
        {% block dostavka_detail %}{% endblock %}
        {% block test %}{% endblock %}
        {% block zakaz %}{% endblock %}
        {% block zakaz_add %}{% endblock %}
        {% block zakaz_detail %}{%  endblock %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
  </body>
</html>

templates/company_zakaz.html
<html>
	<div>
		{% for i in zakaz %}
		{{ i.id }}
		{{ i.create_at }} 
		<a href="zakaz_detail/{{ i.id }}">{{ i.company }} </a>
		{{ i.score }} 
		{{ i.code }} 
		{{ i.name }} 
		{{ i.col }} 
		{{ i.price }} 
		{{ i.price_sel }} 
		{{ i.manager }} 
		{{ i.status }} <br>
		{%endfor%}
	</div>
</html>

templates/dostavka.html
{% extends 'base.html' %}

{% block contaner %}

    <div class="container-fluid starter-template">
        <div class="row">
            <div class="col-lg-3 col-lg-offset-9">
		        <form action="">
			        <select name="test_field">
				        <option value="id">id</option>
			    	    <option value="company">компания</option>
				        <option value="price">счет</option>
			        </select>
			        <input type="text" name="search" placeholder="Введите счет">
			        <input type="submit">
		        </form>
             </div>
        </div>
	</div>
        <div class="row">
            <div class="table-responsive">
                <table class="table table-hover table-condensed">
                    <thead>
                    <tr class="text-center">
                        <th>№ п/п</th>
                        <th>Дата создания</th>
                        <th>Дата доставки</th>
                        <th>Компания</th>
                        <th>Адрес доставки</th>
                        <th>Счет</th>
                        <th>Примечание</th>
                        <th>Менеджер</th>
                        <th>Статус</th>
                    </tr>
                    </thead>
                    {% for objects in all_dos %}
                        <tr>
                            <td class="text-center">{{ forloop.counter }}.</td>
                            <td>{{ objects.create_at | date:"d.m.Y" }}</td>
                            <td>{{ objects.data_dostavki | date:"d.m.Y"}}</td>
                            <td><a href="{% url 'dostavka:detail' objects.pk %}">{{ objects.company }}</a></td>
                            <td>{{ objects.adress }}</td>
                            <td>{{ objects.score }}</td>
                            <td>{{ objects.note }}</td>
                            <td>{{ objects.manager }}</td>
                            <td></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
{% endblock %}

templates/dostavka_add.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block test %}
    <div class="container starter-template">
        <form action="" method="post">{% csrf_token %}
            <div>
                {{ form.as_p }}
            </div>
                <div class="col-lg-2 col-lg-offset-11">
                    <button type="submit" class="btn btn-default">Добавить</button>
                </div>
        </form>
    </div>
{% endblock %}

templates/dostavka_detail.html
{% extends 'base.html' %}

{% block dostavka_detail %}
<div class="container starter-template">
        <form action="" method="post">{% csrf_token %}
            <div>
                {{ form.as_p }}
            </div>
                <div class="col-lg-2 col-lg-offset-11">
                    <button type="submit" class="btn btn-default">Сохранить</button>
                </div>
        </form>
    </div>
{% endblock %}

templates/dostavka_new.html
{% extends 'base.html' %}

{% block contaner %}
    <div class="container-fluid starter-template">
        <div class="row">
            <div class="col-lg-1">
                <form action="today">
                    <input class="btn btn-default" type="submit" value="Сегодня">
                </form>
            </div>
            <div class="col-lg-1 col-lg-offset-6">
                <form action="add">
                    <input class="btn btn-default "type="submit" value="Добавить">
                </form>
            </div>
            <div class="col-lg-4">
                <form class="form-inline" action="">
                <select class="form-control" name="test_field">
				    <option value="company">Компания</option>
			        <option value="data_dostavki">Дата доставки</option>
				    <option value="score">Счет</option>
			    </select>
			        <input class="form-control" type="text" name="search" placeholder="Введите счет">
			        <input  class="btn btn-default" type="submit">
		        </form>
             </div>
         </div>
        <br>
        <div class="row">
            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <tr class="text-center text-capitalize success">
                        <td>№ п/п</td>
                        <td>Дата доставки</td>
                        <td>Компания</td>
                        <td>Адрес доставки</td>
                        <td>Счет</td>
                        <td>Примечание</td>
                        <td>Менеджер</td>
                        <td>Дата создания</td>
                    </tr>
                     {%  for dostavka_item in dostavka %}
                        <tr>
                            <td class="text-center">{{ forloop.counter }}.</td>
                            <td>{{ dostavka_item.data_dostavki | date:"d.m.Y"  }}</td>
                            <td><a href="{% url 'dostavka:detail' dostavka_item.pk %}">{{ dostavka_item.company }}</a></td>
                            <td>{{ dostavka_item.adress }}</td>
                            <td>{{ dostavka_item.score }}</td>
                            <td>{{ dostavka_item.note }}</td>
                            <td>{{ dostavka_item.manager }}</td>
                            <td>{{ dostavka_item.create_at | date:"d.m.Y" }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 col-md-offset-4 text-center">
            {% if dostavka.has_previous %}
                <a href="?page={{ dostavka.previous_page_number }}">←</a>
            {% endif %}

             {% for num in dostavka.paginator.page_range %}
                {% if num == dostavka.number %}
                    <span class="current"><b>{{ num }}</b></span>
                {% else %}
                    <a href="?page={{ num }}"> {{ num }}</a>
                {% endif %}
             {% endfor %}

             {% if article_list.has_next %}
                <a href="?page={{ article_list.next_page_number }}">→</a>
             {% endif %}
         </div>
    </div>
{% endblock %}

templates/dostavka_today.html
{% extends 'base.html' %}

{% block contaner %}
    <div class="container-fluid starter-template">
        <div class="row">
            <div class="col-lg-1">
                <form action="../">
                    <input class="btn btn-default" type="submit" value="Назад">
                </form>
            </div>
            <div class="col-lg-1 col-lg-offset-6">
                <form action="../add">
                    <input class="btn btn-default "type="submit" value="Добавить">
                </form>
            </div>
            <div class="col-lg-4">
                <form class="form-inline" action="">
                <select class="form-control" name="test_field">
				    <option value="company">Компания</option>
			        <option value="data_dostavki">Дата доставки</option>
				    <option value="score">Счет</option>
			    </select>
			        <input class="form-control" type="text" name="search" placeholder="Введите счет">
			        <input  class="btn btn-default" type="submit">
		        </form>
             </div>
         </div>
        <br>
        <div class="row">
            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <tr class="text-center text-capitalize success">
                        <td>№ п/п</td>
                        <td>Дата доставки</td>
                        <td>Компания</td>
                        <td>Адрес доставки</td>
                        <td>Счет</td>
                        <td>Примечание</td>
                        <td>Менеджер</td>
                        <td>Дата создания</td>
                    </tr>
                     {%  for dostavka_item in dostavka %}
                        <tr>
                            <td class="text-center">{{ forloop.counter }}.</td>
                            <td>{{ dostavka_item.data_dostavki | date:"d.m.Y"  }}</td>
                            <td><a href="{% url 'dostavka:detail' dostavka_item.pk %}">{{ dostavka_item.company }}</a></td>
                            <td>{{ dostavka_item.adress }}</td>
                            <td>{{ dostavka_item.score }}</td>
                            <td>{{ dostavka_item.note }}</td>
                            <td>{{ dostavka_item.manager }}</td>
                            <td>{{ dostavka_item.create_at | date:"d.m.Y" }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 col-md-offset-4 text-center">
            {% if dostavka.has_previous %}
                <a href="?page={{ dostavka.previous_page_number }}">←</a>
            {% endif %}

             {% for num in dostavka.paginator.page_range %}
                {% if num == dostavka.number %}
                    <span class="current"><b>{{ num }}</b></span>
                {% else %}
                    <a href="?page={{ num }}"> {{ num }}</a>
                {% endif %}
             {% endfor %}

             {% if article_list.has_next %}
                <a href="?page={{ article_list.next_page_number }}">→</a>
             {% endif %}
         </div>
    </div>
{% endblock %}

templates/index.html
<html>
    <head>
    </head>
	<div>
		<h1>Главная страница</h1>
	</div>
	<div>
		{% for i in test %}	
		{{ i.id }}
		{{ i.create_at }} 
		<a href="zakaz_detail/{{ i.id }}">{{ i.company }} </a>
		{{ i.score }} 
		{{ i.code }} 
		{{ i.name }} 
		{{ i.col }} 
		{{ i.price }} 
		{{ i.price_sel }} 
		{{ i.manager }} 
		{{ i.status }} <br>
		{% endfor %}
	</div>
	<div>
	<form action="zakaz_add">
		<button type="submit">Добавить</button>
	</form>
	</div>
	<div>
	<form action="company_zakaz">
		<button type="submit">Фильтр</button>
	</form>
	</div>
	<div>
	<form action="test">
		<button type="submit">test</button>
	</form>
	</div>
</html>

templates/zakaz.html
{% extends 'base.html' %}
{% block zakaz %}
<div class="container-fluid">
	<div class="starter-template">
        <div class="row">
            <div class="col-lg-3 col-lg-offset-9">
		        <form action="">
			        <select name="test_field">
				        <option value="id">id</option>
			    	    <option value="company">компания</option>
				        <option value="price">счет</option>
			        </select>
			        <input type="text" name="search" placeholder="Введите счет">
			        <input type="submit">
		        </form>
             </div>
        </div>
	</div>
	<div class="row">
        <div class="col-lg-12">
            <div class="table-responsive ">
                <table class="table table-hover table-condensed">
                    <thead>
                    <tr class="text-center">
                        <th>№ п/п</th>
                        <th>Дата создания</th>
                        <th>Компания</th>
                        <th>Счет</th>
                        <th>Артикул</th>
                        <th>Наименование</th>
                        <th>Кол-во</th>
                        <th>Цена закупки</th>
                        <th>Цена продажи</th>
                        <th>Менеджер</th>
                        <th>Статус</th>
                    </tr>
                    </thead>
                {% for i in object_list %}
                    <tr>
		                <td>{{ forloop.counter }}.</td>
		                <td>{{ i.create_at | date:"d.m.Y" }}</td>
                        <td> <a href="zakaz_detail/{{ i.id }}">{{ i.company }} </a></td>
		                <td>{{ i.score }}</td>
		                <td>{{ i.code }}</td>
		                <td>{{ i.name }}</td>
		                <td>{{ i.col }}</td>
		                <td>{{ i.price }}</td>
		                <td>{{ i.price_sel }}</td>
		                <td>{{ i.manager }}</td>
		                <td>{{ i.status }} </td>
                    </tr>
                {% endfor %}
                </table>
            </div>
        </div>
	</div>
	<div class="col-lg-1">
	<form action="zakaz_add">
		<button class="btn btn-default" type="submit">Добавить</button>
	</form>
	</div>
	<div class="col-lg-1 ">
	<form action="company_zakaz">
		<button class="btn btn-default" type="submit">Фильтр</button>
	</form>
	</div>
</div>
{% endblock %}

templates/zakaz_add.html
{% extends 'base.html' %}
{% block zakaz_add %}
    <div>
		<h2>
			Страница заказа
		</h2>
	</div>
	<div>
		<form class="form-horizontal" action="" method="post">{% csrf_token %}
		        {{ form.as_p }}
		<div>
			<button type="submit">Отправить</button>
		</div>
		</form>
	</div>
{% endblock %}

templates/zakaz_detail.html
{% extends 'base.html' %}
{% block zakaz_detail %}
    <div>
		<h2>
			Информация о заказе
		</h2>
	</div>
	<div>
		{{ form.as_p }}
	</div>
{%  endblock %}